# ============================================================
# pytest_script.py
# Auto-Generated Pytest Script
# Test Case ID  : TC-83
# QTest ID      : 11194292
# Test Name     : Successful Login with Valid Username and Password
# Priority      : High
# Status        : New
# Description   : Verify that a registered user can successfully log in
#                 using valid username and password.
#                 Linked to SAUC-3 - User Login with Username and Password.
# Generated By  : EliteA Automation Agent
# ============================================================

import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


# ─────────────────────────────────────────────
# Configuration / Constants
# ─────────────────────────────────────────────
BASE_URL        = "https://your-application-url.com/login"   # 🔧 Replace with actual URL
VALID_USERNAME  = "valid_test_user"                          # 🔧 Replace with actual username
VALID_PASSWORD  = "valid_test_password"                      # 🔧 Replace with actual password
TIMEOUT         = 10  # seconds


# ─────────────────────────────────────────────
# Fixtures
# ─────────────────────────────────────────────
@pytest.fixture(scope="function")
def driver():
    """
    Fixture: Initialise and tear down the WebDriver session.
    Scope: function – a fresh browser is created for each test.
    """
    options = webdriver.ChromeOptions()
    options.add_argument("--headless")          # Remove flag to run with UI
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("--window-size=1920,1080")

    driver = webdriver.Chrome(options=options)
    driver.implicitly_wait(TIMEOUT)
    yield driver
    driver.quit()


# ─────────────────────────────────────────────
# Helper Utilities
# ─────────────────────────────────────────────
def wait_for_element(driver, by, locator, timeout=TIMEOUT):
    """Wait until an element is visible and return it."""
    return WebDriverWait(driver, timeout).until(
        EC.visibility_of_element_located((by, locator))
    )


def wait_for_url_change(driver, partial_url, timeout=TIMEOUT):
    """Wait until the current URL contains the expected partial string."""
    return WebDriverWait(driver, timeout).until(
        EC.url_contains(partial_url)
    )


# ─────────────────────────────────────────────
# Test Class
# ─────────────────────────────────────────────
class TestTC83_SuccessfulLogin:
    """
    Test Suite  : TC-83 – Successful Login with Valid Username and Password
    QTest ID    : 11194292
    Description : Verify that a registered user can successfully log in
                  using valid credentials.
    """

    # ----------------------------------------------------------
    # Test Step 1:
    # Description : Navigate to the application login page
    # Expected    : Login page is displayed with username, password
    #               fields and Login button
    # ----------------------------------------------------------
    def test_step_01_navigate_to_login_page(self, driver):
        """TC-83 | Step 1 – Navigate to the application login page."""
        driver.get(BASE_URL)

        username_field = wait_for_element(driver, By.ID, "username")
        password_field = wait_for_element(driver, By.ID, "password")
        login_button   = wait_for_element(driver, By.ID, "loginBtn")

        assert username_field.is_displayed(), \
            "❌ FAIL: Username field is NOT displayed on the login page."
        assert password_field.is_displayed(), \
            "❌ FAIL: Password field is NOT displayed on the login page."
        assert login_button.is_displayed(), \
            "❌ FAIL: Login button is NOT displayed on the login page."

        print("✅ PASS: Login page displayed with all required fields.")

    # ----------------------------------------------------------
    # Test Step 2:
    # Description : Enter a valid registered username in the Username field
    # Expected    : Username is entered successfully
    # ----------------------------------------------------------
    def test_step_02_enter_valid_username(self, driver):
        """TC-83 | Step 2 – Enter a valid registered username."""
        driver.get(BASE_URL)

        username_field = wait_for_element(driver, By.ID, "username")
        username_field.clear()
        username_field.send_keys(VALID_USERNAME)

        assert username_field.get_attribute("value") == VALID_USERNAME, \
            "❌ FAIL: Username was NOT entered correctly in the Username field."

        print(f"✅ PASS: Username '{VALID_USERNAME}' entered successfully.")

    # ----------------------------------------------------------
    # Test Step 3:
    # Description : Enter the corresponding valid password in the Password field
    # Expected    : Password is masked and entered successfully
    # ----------------------------------------------------------
    def test_step_03_enter_valid_password(self, driver):
        """TC-83 | Step 3 – Enter the corresponding valid password."""
        driver.get(BASE_URL)

        password_field = wait_for_element(driver, By.ID, "password")
        password_field.clear()
        password_field.send_keys(VALID_PASSWORD)

        field_type = password_field.get_attribute("type")
        assert field_type == "password", \
            f"❌ FAIL: Password field type is '{field_type}' – expected 'password' (masked)."
        assert password_field.get_attribute("value") == VALID_PASSWORD, \
            "❌ FAIL: Password was NOT entered correctly in the Password field."

        print("✅ PASS: Password entered and masked successfully.")

    # ----------------------------------------------------------
    # Test Step 4:
    # Description : Click the 'Login' button
    # Expected    : User is redirected to the dashboard/home page successfully
    # ----------------------------------------------------------
    def test_step_04_click_login_and_verify_redirect(self, driver):
        """TC-83 | Step 4 – Click 'Login' and verify redirect to dashboard."""
        driver.get(BASE_URL)

        username_field = wait_for_element(driver, By.ID, "username")
        password_field = wait_for_element(driver, By.ID, "password")
        login_button   = wait_for_element(driver, By.ID, "loginBtn")

        username_field.clear()
        username_field.send_keys(VALID_USERNAME)

        password_field.clear()
        password_field.send_keys(VALID_PASSWORD)

        login_button.click()

        # Verify redirection to dashboard/home page
        wait_for_url_change(driver, "dashboard")
        current_url = driver.current_url

        assert "dashboard" in current_url or "home" in current_url, \
            f"❌ FAIL: User was NOT redirected to dashboard. Current URL: {current_url}"

        print(f"✅ PASS: User successfully redirected to: {current_url}")

    # ----------------------------------------------------------
    # End-to-End Test (All Steps Combined)
    # ----------------------------------------------------------
    def test_TC83_full_login_flow(self, driver):
        """
        TC-83 | Full End-to-End – Successful Login with Valid Credentials.
        Covers all 4 steps in sequence:
          1. Navigate to login page
          2. Enter valid username
          3. Enter valid password
          4. Click Login → verify dashboard redirect
        """
        # ── Step 1: Navigate to login page ──────────────────────
        driver.get(BASE_URL)
        username_field = wait_for_element(driver, By.ID, "username")
        password_field = wait_for_element(driver, By.ID, "password")
        login_button   = wait_for_element(driver, By.ID, "loginBtn")

        assert username_field.is_displayed(), "❌ FAIL Step 1: Username field not visible."
        assert password_field.is_displayed(), "❌ FAIL Step 1: Password field not visible."
        assert login_button.is_displayed(),   "❌ FAIL Step 1: Login button not visible."
        print("✅ Step 1 PASS: Login page loaded with all fields.")

        # ── Step 2: Enter valid username ─────────────────────────
        username_field.clear()
        username_field.send_keys(VALID_USERNAME)
        assert username_field.get_attribute("value") == VALID_USERNAME, \
            "❌ FAIL Step 2: Username not entered correctly."
        print(f"✅ Step 2 PASS: Username '{VALID_USERNAME}' entered.")

        # ── Step 3: Enter valid password ─────────────────────────
        password_field.clear()
        password_field.send_keys(VALID_PASSWORD)
        assert password_field.get_attribute("type") == "password", \
            "❌ FAIL Step 3: Password field is not masked."
        assert password_field.get_attribute("value") == VALID_PASSWORD, \
            "❌ FAIL Step 3: Password not entered correctly."
        print("✅ Step 3 PASS: Password entered and masked.")

        # ── Step 4: Click Login → verify redirect ────────────────
        login_button.click()
        wait_for_url_change(driver, "dashboard")
        current_url = driver.current_url
        assert "dashboard" in current_url or "home" in current_url, \
            f"❌ FAIL Step 4: Not redirected to dashboard. URL={current_url}"
        print(f"✅ Step 4 PASS: Redirected to dashboard → {current_url}")

        print("\n🎉 TC-83 FULL FLOW PASSED — Successful Login with Valid Credentials.")


# ─────────────────────────────────────────────
# Entry Point
# ─────────────────────────────────────────────
if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
